package:
  name: ros-humble-kinematics-interface-kdl
  version: 0.0.2
source:
  git_url: https://github.com/ros2-gbp/kinematics_interface-release.git
  git_rev: release/humble/kinematics_interface_kdl/0.0.2-1
  folder: ros-humble-kinematics-interface-kdl/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 1
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake 3.23
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - eigen
    - python
    - ros-humble-ament-cmake
    - ros-humble-ament-cmake-gmock
    - ros-humble-eigen3-cmake-module
    - ros-humble-kdl-parser
    - ros-humble-kinematics-interface
    - ros-humble-pluginlib
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-ros2-control-test-assets
    - ros-humble-tf2-eigen-kdl
    - ros2-distro-mutex 0.1 humble
  run:
    - eigen
    - python
    - ros-humble-kdl-parser
    - ros-humble-kinematics-interface
    - ros-humble-pluginlib
    - ros-humble-ros-workspace
    - ros-humble-tf2-eigen-kdl
    - ros2-distro-mutex 0.1 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
