package:
  name: ros-humble-sdformat-urdf
  version: 1.0.1
source:
  git_url: https://github.com/ros2-gbp/sdformat_urdf-release.git
  git_rev: release/humble/sdformat_urdf/1.0.1-1
  folder: ros-humble-sdformat-urdf/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 1
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake 3.23
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - libsdformat12
    - python
    - ros-humble-ament-cmake-gtest
    - ros-humble-ament-cmake-ros
    - ros-humble-ament-lint-auto
    - ros-humble-ament-lint-common
    - ros-humble-pluginlib
    - ros-humble-rcutils
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-sdformat-test-files
    - ros-humble-tinyxml2-vendor
    - ros-humble-urdf
    - ros-humble-urdf-parser-plugin
    - ros2-distro-mutex 0.1 humble
    - urdfdom_headers
  run:
    - libsdformat12
    - python
    - ros-humble-ament-cmake-ros
    - ros-humble-pluginlib
    - ros-humble-rcutils
    - ros-humble-ros-workspace
    - ros-humble-tinyxml2-vendor
    - ros-humble-urdf
    - ros-humble-urdf-parser-plugin
    - ros2-distro-mutex 0.1 humble
    - urdfdom_headers
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
