jobs:
  stage_0_job_0:
    name: nav2-collision-monitor ament-cmake-clang-format rosbag2-storage-mcap-testdata
      mcap-vendor
    runs-on: macOS-11
    strategy:
      fail-fast: false
    needs: []
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-nav2-collision-monitor ros-humble-ament-cmake-clang-format
        ros-humble-rosbag2-storage-mcap-testdata ros-humble-mcap-vendor
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-nav2-collision-monitor ros-humble-ament-cmake-clang-format
          ros-humble-rosbag2-storage-mcap-testdata ros-humble-mcap-vendor
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx_arm64.sh
  stage_1_job_1:
    name: rosbag2-storage-mcap
    runs-on: macOS-11
    strategy:
      fail-fast: false
    needs:
    - stage_0_job_0
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-rosbag2-storage-mcap
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rosbag2-storage-mcap
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx_arm64.sh
name: build_osx
on:
  push:
    branches:
    - buildbranch_osx_arm64
